# Generated by Django 6.0.3 on 2026-04-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('forming', 'Формируется'), ('active', 'Активный'), ('completed', 'Завершен')], default='forming', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='position',
            name='status',
            field=models.CharField(choices=[('in_work', 'В работе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='in_work', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
