# Generated by Django 6.0.3 on 2026-04-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_supplier_created_by_user_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лот', 'verbose_name_plural': 'Лоты'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['id'], 'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
        migrations.AlterModelOptions(
            name='sheet',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Инженерный лист', 'verbose_name_plural': 'Инженерные листы'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AddField(
            model_name='lot',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок поставки'),
        ),
        migrations.AddField(
            model_name='lot',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='lot',
            name='final_document',
            field=models.FileField(blank=True, null=True, upload_to='lots/documents/', verbose_name='Итоговый документ'),
        ),
        migrations.AddField(
            model_name='lot',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='tenders.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='lot',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Итоговая цена'),
        ),
        migrations.AddField(
            model_name='position',
            name='winner_supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название поставщика (текст)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='kpp',
            field=models.CharField(blank=True, max_length=20, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('tor', 'Техническое задание'), ('commercial', 'Коммерческое предложение'), ('drawing', 'Чертеж'), ('final', 'Итоговый документ'), ('protocol', 'Протокол'), ('contract', 'Договор')], max_length=20, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='status',
            field=models.CharField(choices=[('forming', 'Формируется'), ('active', 'Активный'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='forming', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='position',
            name='unit',
            field=models.CharField(default='шт', max_length=20, verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='position',
            name='winner_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_positions', to='tenders.supplier', verbose_name='Поставщик-победитель'),
        ),
    ]
