# Generated by Django 6.0.3 on 2026-04-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_alter_comment_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
    ]
